/* global Deno */

import fs from 'node:fs'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import process from 'node:process'
import { setInterval, clearInterval } from 'node:timers'
import { writeHeapSnapshot } from 'node:v8'

import { execFile } from 'npm:@steve02081504/exec'
import { on_shutdown } from 'npm:on-shutdown'

import { git } from '../scripts/git.mjs'
import { console } from '../scripts/i18n/index.mjs'
import { ms } from '../scripts/ms.mjs'
import { runWorker } from '../workers/index.mjs'

/** 堆采样间隔。 */
const SAMPLE_INTERVAL_MS = ms('30s')
/** 持续走高的判定窗口。 */
const RISE_WINDOW_MS = ms('5m')
/** 触发后的冷却时间。 */
const COOLDOWN_MS = ms('6h')
/** 触发阈值 = 启动基线堆 × 倍数。 */
const THRESHOLD_MULT = 2
/** 分析报告 top N。 */
const ANALYSIS_TOP_N = 40
/** 目标仓库。 */
const REPORT_REPO = 'steve02081504/fount'
/** gh 子进程超时。 */
const GH_TIMEOUT_MS = 20_000

/**
 * 在 data 下返回 heapsnapshots 目录。
 * @param {string} dataPath 应用数据目录
 * @returns {string} 快照目录
 */
function heapSnapshotDir(dataPath) {
	return path.join(dataPath, 'heapsnapshots')
}

/**
 * 在分析工作线程中聚合 .heapsnapshot 的 top 分配者。
 * @param {string} snapshotPath 快照绝对路径
 * @param {string} outPath 报告输出路径
 * @returns {Promise<{ text: string, outPath: string }>} 报告文本
 */
function analyzeHeapSnapshot(snapshotPath, outPath) {
	return new Promise((resolve, reject) => {
		const worker = runWorker('heapSnapshotAnalyzer')
		/**
		 * 处理工作线程结果消息。
		 * @param {MessageEvent} event 结果消息
		 * @returns {void}
		 */
		worker.onmessage = event => {
			worker.terminate()
			if (event.data?.type === 'resolve') resolve(event.data.data)
			else reject(new Error(String(event.data?.data)))
		}
		/**
		 * 处理工作线程错误。
		 * @param {ErrorEvent} event 错误事件
		 * @returns {void}
		 */
		worker.onerror = event => {
			worker.terminate()
			reject(event.error ?? new Error('heapSnapshotAnalyzer worker error'))
		}
		worker.postMessage({ type: 'analyze', snapshotPath, outPath, topN: ANALYSIS_TOP_N })
	})
}

/**
 * 探测 gh 是否可用且已登录。
 * @returns {Promise<boolean>} 可用即返回 true
 */
async function ghReady() {
	const timeout = { signal: AbortSignal.timeout(GH_TIMEOUT_MS) }
	try {
		if ((await execFile('gh', ['--version'], timeout)).code !== 0) return false
		return (await execFile('gh', ['auth', 'status'], timeout)).code === 0
	}
	catch {
		return false
	}
}

/**
 * 读取去重记录。
 * @param {string} dir 快照目录
 * @returns {{ byCommit: Record<string, { issueUrl: string | null, at: number }> }} 记录
 */
function readReportRecord(dir) {
	try {
		return JSON.parse(fs.readFileSync(path.join(dir, 'reports.json'), 'utf8'))
	}
	catch {
		return { byCommit: {} }
	}
}

/**
 * 写入去重记录。
 * @param {string} dir 快照目录
 * @param {object} record 记录
 * @returns {void}
 */
function writeReportRecord(dir, record) {
	fs.mkdirSync(dir, { recursive: true })
	fs.writeFileSync(path.join(dir, 'reports.json'), `${JSON.stringify(record, null, '\t')}\n`, 'utf8')
}

/**
 * 用 gh 在 fount 仓库开 issue。
 * @param {string} title 标题
 * @param {string} body 正文
 * @returns {Promise<string | null>} issue URL
 */
async function ghCreateIssue(title, body) {
	const dir = await mkdtemp(path.join(tmpdir(), 'fount-heap-'))
	const bodyFile = path.join(dir, 'body.md')
	try {
		await writeFile(bodyFile, body, 'utf8')
		const result = await execFile('gh', [
			'issue', 'create', '--repo', REPORT_REPO, '--title', title, '--body-file', bodyFile,
		], { signal: AbortSignal.timeout(GH_TIMEOUT_MS) })
		if (result.code !== 0) return null
		return (result.stdout ?? result.stdall ?? '').trim().split('\n').pop() || null
	}
	finally {
		await rm(dir, { recursive: true, force: true })
	}
}

/**
 * 获取 fount 当前提交 hash；非 git 仓库时回退 'unknown'。
 * @returns {Promise<string>} commit hash
 */
async function resolveCommitHash() {
	try {
		return await git('rev-parse HEAD') || 'unknown'
	}
	catch {
		return 'unknown'
	}
}

/**
 * 拼接上报 issue 正文。
 * @param {object} info 报告信息
 * @param {string} info.commitHash fount 提交 hash
 * @param {string} info.denoVersion Deno 版本
 * @param {number} info.baselineHeap 基线堆字节
 * @param {number} info.triggerHeap 触发时堆字节
 * @param {string} info.snapshotPath 快照绝对路径
 * @param {string} info.reportText 分析报告文本
 * @returns {string} markdown 正文
 */
function buildIssueBody({ commitHash, denoVersion, baselineHeap, triggerHeap, snapshotPath, reportText }) {
	return `\
This issue was auto-generated by fount after detecting sustained heap growth.

- **fount commit**: \`${commitHash}\`
- **Deno version**: \`${denoVersion}\`
- **heap baseline** (\`config.prelaunch.heapSize\`): \`${baselineHeap}\` bytes
- **heap at trigger**: \`${triggerHeap}\` bytes
- **heapsnapshot**: \`${snapshotPath}\`

<details><summary>Top allocators by self_size</summary>

\`\`\`
${reportText}
\`\`\`

</details>
`
}

/**
 * 上报堆增长：先写快照 + 分析报告，再经 gh 开 issue（按 commit 去重）。
 * @param {object} params 参数
 * @param {string} params.dataPath 应用数据目录
 * @param {number} params.baselineHeap 基线堆字节
 * @param {number} params.triggerHeap 触发时堆字节
 * @returns {Promise<void>}
 */
async function reportHeapGrowth({ dataPath, baselineHeap, triggerHeap }) {
	const dir = heapSnapshotDir(dataPath)
	const commitHash = await resolveCommitHash()
	const denoVersion = typeof Deno?.version?.deno === 'string' ? Deno.version.deno : 'unknown'

	const record = readReportRecord(dir)
	if (record.byCommit[commitHash]) {
		console.warnI18n('fountConsole.heapGrowth.alreadyReported', { commit: commitHash })
		return
	}

	fs.mkdirSync(dir, { recursive: true })
	const stamp = new Date().toISOString().replace(/[:.]/g, '-')
	const snapshotPath = writeHeapSnapshot(path.join(dir, `Heap-${stamp}-${process.pid}.heapsnapshot`))
	console.logI18n('fountConsole.heapGrowth.snapshotSaved', { path: snapshotPath })

	const outPath = `${snapshotPath}.analysis.txt`
	let reportText
	try {
		const result = await analyzeHeapSnapshot(snapshotPath, outPath)
		reportText = result.text
	}
	catch (error) {
		console.warnI18n('fountConsole.heapGrowth.analysisFailed', { error: error?.message || String(error) })
		reportText = `(analysis failed: ${error?.message || String(error)})`
	}

	if (!await ghReady()) {
		record.byCommit[commitHash] = { issueUrl: null, at: Date.now() }
		writeReportRecord(dir, record)
		console.warnI18n('fountConsole.heapGrowth.ghUnavailable', { commit: commitHash })
		return
	}

	const title = `[fount auto-report] Sustained heap growth (~${Math.round(triggerHeap / 1024 / 1024)} MB)`
	const issueUrl = await ghCreateIssue(title, buildIssueBody({
		commitHash,
		denoVersion,
		baselineHeap,
		triggerHeap,
		snapshotPath,
		reportText,
	}))

	record.byCommit[commitHash] = { issueUrl: issueUrl ?? null, at: Date.now() }
	writeReportRecord(dir, record)

	if (!issueUrl)
		console.errorI18n('fountConsole.heapGrowth.publishFailed', { commit: commitHash })
	else
		console.logI18n('fountConsole.heapGrowth.published', { url: issueUrl })
}

/**
 * 启动堆增长监控：堆连续走高且超过基线 × 倍数达 5 分钟时，保存 heapsnapshot 并经 gh 上报。
 * @param {object} options 配置
 * @param {object} options.config 应用配置（含 prelaunch.heapSize）
 * @param {string} options.data_path 应用数据目录
 * @param {() => number} options.getMemoryUsage 当前堆占用（字节）
 * @returns {void}
 */
export function startHeapGrowthMonitor({ config, data_path, getMemoryUsage }) {
	let baselineHeap = Number(config.prelaunch?.heapSize) > 0 ? Number(config.prelaunch.heapSize) : null
	/** 触发阈值 = 基线堆 × 倍数。
	 * @returns {number} 阈值字节
	 */
	const threshold = () => Math.round((baselineHeap ?? 0) * THRESHOLD_MULT)

	let riseStart = 0
	let lastHeap = 0
	let cooldownUntil = 0
	let intervalId = null

	/** 采样心跳：判定堆是否持续走高。 */
	const tick = () => {
		const now = Date.now()
		const heap = getMemoryUsage()
		if (baselineHeap === null) baselineHeap = heap

		if (heap < threshold()) { riseStart = 0; lastHeap = heap; return }
		if (!riseStart) { riseStart = now; lastHeap = heap; return }
		if (heap < lastHeap) { riseStart = now; lastHeap = heap; return }
		lastHeap = heap
		if (now - riseStart < RISE_WINDOW_MS || now < cooldownUntil) return

		cooldownUntil = now + COOLDOWN_MS
		riseStart = 0
		lastHeap = 0
		reportHeapGrowth({ dataPath: data_path, baselineHeap, triggerHeap: heap }).catch(error => {
			console.warnI18n('fountConsole.heapGrowth.reportFailed', { error: error?.message || String(error) })
		})
	}

	intervalId = setInterval(tick, SAMPLE_INTERVAL_MS).unref()
	on_shutdown(() => clearInterval(intervalId))
}
