version: "3"

services:
  fount:
    container_name: fount
    image: steve02081504/fount:latest
    ports:
      - "8931:8931"
    volumes:
      - ./data:/app/data:rw # 挂载 data 目录以存储用户数据
      - ./node_modules:/app/node_modules:rw # 挂载 node_modules 目录以缓存用户数据产生的依赖项
    restart: unless-stopped
