function script:Initialize-FountFavicon {
	$iconPath = "$FOUNT_DIR/src/public/pages/favicon.ico"
	if (Test-Path -LiteralPath $iconPath) { return }
	Write-Host (Get-I18n -key 'install.compilingFavicon')
	run shutdown
	$global:LastExitCode = 0
}

function script:Send-Ps12exeThrowIssue($errorRecord) {
	if (-not (Get-Command gh -ErrorAction Ignore)) { return }
	try {
		gh auth status 2>&1 | Out-Null
		if ($LastExitCode -ne 0) { return }
		$repo = 'steve02081504/ps12exe'
		$query = 'ps12exe throws terminating errors instead of only setting LastExitCode'
		$list = @(ConvertFrom-Json (gh issue list --repo $repo --search $query --state all --json url --limit 1 | Out-String))
		if ($LastExitCode -ne 0) { return }
		if ($list.Count -and $list[0].url) { return }
		$temporaryFilePath = [IO.Path]::GetTempFileName()
		try {
			[IO.File]::WriteAllText($temporaryFilePath, @'
This issue was auto-generated by [fount](https://github.com/steve02081504/fount) after ps12exe threw during optional fount.exe compilation.

Documented contract: report failure via `$LastExitCode` only (0/1/2/3). Do not throw, and do not `Write-Error` (it appends to `$Error`).

```
'@ + [string]$errorRecord + @'

```
'@)
			gh issue create --repo $repo --title $query --body-file $temporaryFilePath | Out-Null
		}
		finally {
			Remove-Item -LiteralPath $temporaryFilePath -Force -ErrorAction Ignore
		}
	}
	catch { }
}

function script:New-FountExe($executablePath = "fount.exe") {
	# $null skips PowerShell default values.
	if (-not $executablePath) { $executablePath = "fount.exe" }
	Initialize-FountFavicon
	Test-PWSHModule ps12exe
	# Contract: ps12exe fails via $LastExitCode only (steve02081504/ps12exe#58).
	# This try/catch stays glued to the ps12exe call — report every throw, do not rethrow.
	# geneexe sees $Error / $LastExitCode via index.ps1. Do not move Send-Ps12exeThrowIssue.
	try {
		ps12exe -inputFile "$FOUNT_DIR/src/runner/main.ps1" -outputFile $executablePath
	}
	catch {
		Send-Ps12exeThrowIssue $_
	}
}
