name: 'bug report🕷'
description: help us improve
title: a bug
labels: bug
assignees: steve02081504
body:
  - type: checkboxes
    attributes:
      label: 检查清单 Prerequisites
      options:
        - label: "请确保你是在最新版本中遇见此问题\nMake sure you have this bug in the latest release"
          id: latest-release
          required: true
        - label: "请确保你已经检索了已关闭的问题，以确保你的问题没有被重复提交\nMake sure you have retrieved closed issues to make sure your issue has not been submitted repeatedly"
          id: closed-issues
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: "描述错误\nDescribe the bug"
      description: |
        对错误的清晰简明的描述于此
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: fount-usage
    attributes:
      label: "复现\nTo Reproduce"
      description: |
        你如何使用fount
        How do you use fount.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "预期行为\nExpected behavior"
      description: |
        对你期望发生的事的清晰而简明的描述
        A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshorts
    attributes:
      label: "截图\nScreenshots"
      description: |
        如果可以，请添加截图以帮助解释你的问题
        If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional-context
    attributes:
      label: "附加上下文\nAdditional context"
      description: |
        在此处添加有关该问题的任何其他上下文
        Add any other context about the problem here.
