name: "feature request🎨"
description: Suggest idea
title: a feature request
labels: enhancement
assignees: 
  - steve02081504
body:
  - type: checkboxes
    attributes:
      label: 检查清单 Prerequisites
      options:
      - label: "请确保你已经检索了已关闭的问题，以确保你的问题没有被重复提交\nMake sure you have retrieved closed issues to make sure your issue has not been submitted repeatedly"
        id: closed-issues
        required: true

  - type: textarea
    id: problem
    attributes:
      label: "问题描述\nProblem description"
      description: |
        你的建议是否与什么问题有关？请描述一下。
        Is your feature request related to a problem? Please describe.
      placeholder: |
        对你遇见的问题的清晰简明的描述于此
        A clear and concise description of what the problem is.
        例：我总是感到沮丧当 [...]
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "解决方案描述\nSolution description"
      description: |
        描述你想要的解决方案
        Describe the solution you'd like
      placeholder: |
        对你想要的解决方案的清晰简明的描述于此
        A clear and concise description of what you want to happen.
        例：我希望能够 [...]
        Ex. I'd like to see [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "替代方案描述\nAlternative description"
      description: |
        描述你考虑过的替代方案
        Describe alternatives you've considered
      placeholder: |
        对你考虑过的任何替代方案或功能的清晰简明的描述
        A clear and concise description of any alternative solutions or features you've considered.
        例：一种替代性的方案，可以 [...]
        Ex. One alternative solution could be [...]

  - type: textarea
    id: context
    attributes:
      label: "附加内容\nAdditional context"
      description: |
        附加内容
        Additional context
      placeholder: |
        在此处添加有关功能请求的任何其他上下文或屏幕截图
        Add any other context or screenshots about the feature request here.
