name: Set Executable Permissions

permissions:
  contents: write

on:
  push:
    paths:
      - '**.sh'
      - '**.fish'
      - '**.zsh'
      - 'path/**'
  workflow_dispatch:

jobs:
  set-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set execute permission for sh files
        run: |
          chmod +x ./*.sh ./*.fish ./*.zsh ./path/*
      - name: git add all
        run: git add -A
      - name: Push changes
        uses: actions-go/push@master
        with:
          author-email: taromati2@outlook.com
          author-name: Taromati2
          commit-message: 'file update~'
          remote: origin
          token: ${{ secrets.GITHUB_TOKEN }}
