name: Run Tests

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/fount_ci.yaml
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
    with:
      run-step-name: Run tests
      run-command: deno run --allow-scripts --allow-all -c "./deno.json" ./src/scripts/test/cli.mjs
      deno-clean-entrypoints: ./src/scripts/test/cli.mjs
      cache-test-data: true
