name: Verify Shells

on:
  push:
    paths:
      - 'src/public/parts/shells/**'
      - 'deno.json'
      - 'src/server/p2p_server/**'
      - '.github/workflows/verify_shells.yaml'
      - '.github/workflows/verify_shells.mjs'
      - '.github/workflows/fount_ci.yaml'
    tags-ignore:
      - '*'
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  verify-shells:
    uses: ./.github/workflows/fount_ci.yaml
    with:
      run-step-name: Load all shells
      run-command: deno run --allow-scripts --allow-all -c "./deno.json" ./.github/workflows/verify_shells.mjs
      deno-clean-entrypoints: ./.github/workflows/verify_shells.mjs
